# Site settings
title: my:reality
email: miguel-gonzalez@gmx.de
description: Game developer from Germany, Hogwarts student and software engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://my-reality.de" # the base hostname & protocol for your site
twitter_username: tweetmyreality
github_username:  MyRealityCoding
paginate: 6
paginate_path: "/page:num/"

# Build settings
markdown: kramdown

navigation:
- text: Blog
  title: News, Tutorials and more.
  url: /
  icon: terminal
- text: Games
  title: All about my games.
  url: /games/
  icon: gamepad
- text: Media
  title: Videos, images and more.
  url: /media/
  icon: youtube-play
- text: Code
  title: My github account.
  url: https://github.com/MyRealityCoding
  icon: github

games:

- name: Craft
  genre: strategy
  tag: gamedev
  date: not finished
  url: https://github.com/MyRealityCoding/craft#getting-started
- name: YoloWars
  genre: shooter
  tag: gamejam
  date: February 2015
  url: http://bitbrain-gaming.github.io/lgj
- name: NeonWars
  genre: strategy
  tag: 1gam
  date: March 2014
  url:  neonwars
- name: Shiny Avenger
  genre: shooter
  tag: 1gam
  date: February 2014
  url:  http://shinyavenger.my-reality.de
- name: Maze
  genre: arcade
  tag: ggj
  date: January 2014
  url:  maze
- name: Candy Crusher
  genre: action
  tag: candyjam
  date: January 2014
  url: candycrusher
- name: Plox
  genre: shooter
  tag: 1gam
  date: January 2014
  url: plox
- name: AcidSnake
  genre: arcade
  tag: gamedev
  date: August 2013
  url: http://acidsnake.my-reality.de
- name: LittleWars
  genre: strategy
  tag: gamedev
  date: January 2012
  url: littlewars
