# Site settings
title: bitbrain
email: miguel-gonzalez@gmx.de
description: Game developer from Germany, Hogwarts student and software engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://my-reality.de" # the base hostname & protocol for your site
twitter_username: tweetmyreality
github_username:  MyRealityCoding
paginate: 4
paginate_path: "/page:num/"

# Build settings
markdown: kramdown

navigation:
- text: Blog
  title: News, Tutorials and more.
  url: /
  icon: terminal
- text: Games
  title: All about my games.
  url: /games/
  icon: gamepad
- text: Media
  title: Videos, images and more.
  url: /media/
  icon: youtube-play
- text: Code
  title: My github account.
  url: https://github.com/MyRealityCoding
  icon: github
