# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            bitbrain
tagline:          'gamedev. devops. software design.'
description:      'Hello, my name is <a href="https://twitter.com/bitbrain_" target="_blank">Miguel</a> and I talk to Computers. Sometimes even to myself.'
url:              https://bitbrain.github.io

author:
  name:           'Miguel Gonzalez Sanchez'
  url:            https://twitter.com/bitbrain_

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/bitbrain/bitbrain.github.io
